# Generated by Django 6.1 on 2026-10-05 14:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Com ou sem pontuação (ex: 12.345.678/0001-95)', max_length=18, unique=True, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', unique=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Construtora',
                'verbose_name_plural': 'Construtoras',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'Estrutura / Comodidade',
                'verbose_name_plural': 'Estruturas / Comodidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', unique=True, verbose_name='Telefone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('cartographic_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Identificação cartográfica')),
                ('block', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quadra')),
                ('lot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lote')),
                ('sea_distance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distância ao mar (metros)')),
                ('sales_start', models.DateField(verbose_name='Início das vendas')),
                ('delivery_date', models.DateField(verbose_name='Data da entrega')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
            },
        ),
        migrations.CreateModel(
            name='EstateFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (m²)')),
                ('floor', models.CharField(blank=True, max_length=32, null=True, verbose_name='Pavimento / Andar')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.estate', verbose_name='Empreendimento')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.facility', verbose_name='Estrutura')),
            ],
            options={
                'verbose_name': 'Estrutura do Empreendimento',
                'verbose_name_plural': 'Estruturas do Empreendimento',
                'unique_together': {('estate', 'facility')},
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='facilities',
            field=models.ManyToManyField(related_name='estates', through='management.EstateFacility', to='management.facility', verbose_name='Estruturas'),
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Sinal')),
                ('key_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Chaves ou habite-se')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Mensais (%)')),
                ('monthly_installments', models.PositiveIntegerField(verbose_name='Mensais (parcelas)')),
                ('balloon_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Intercaladas (%)')),
                ('balloon_installments', models.PositiveIntegerField(verbose_name='Intercaladas (parcelas)')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.estate', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Condição de pagamento',
                'verbose_name_plural': 'Condições de pagamento',
            },
        ),
    ]
