# Generated by Django 6.1 on 2026-10-08 13:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import management.models
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Com ou sem pontuação (ex: 12.345.678/0001-95)', max_length=18, unique=True, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', unique=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Construtora',
                'verbose_name_plural': 'Construtoras',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='Nome')),
                ('slug', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'Estrutura / Comodidade',
                'verbose_name_plural': 'Estruturas / Comodidades',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', unique=True, verbose_name='Telefone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', management.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ibge_code', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Código IBGE')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['state', 'name'], name='management__state_66b1c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('cep', models.CharField(help_text='Com ou sem traço (ex: 88015-200)', max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=128, verbose_name='Logradouro')),
                ('number', models.CharField(help_text='Use “s/n” se não houver', max_length=16, verbose_name='Número')),
                ('complement', models.CharField(blank=True, default='', max_length=64, verbose_name='Complemento')),
                ('district', models.CharField(max_length=64, verbose_name='Bairro')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitude')),
                ('cartographic_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Identificação cartográfica')),
                ('block', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quadra')),
                ('lot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lote')),
                ('sales_start', models.DateField(verbose_name='Início das vendas')),
                ('delivery_date', models.DateField(verbose_name='Data da entrega')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estates', to='management.city', verbose_name='Município')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
            },
        ),
        migrations.CreateModel(
            name='EstateFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Área total (m²)')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.estate', verbose_name='Empreendimento')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.facility', verbose_name='Estrutura')),
            ],
            options={
                'verbose_name': 'Estrutura do Empreendimento',
                'verbose_name_plural': 'Estruturas do Empreendimento',
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='facilities',
            field=models.ManyToManyField(related_name='estates', through='management.EstateFacility', to='management.facility', verbose_name='Estruturas'),
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Sinal (%)')),
                ('key_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Chaves ou habite-se (%)')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Mensais (%)')),
                ('monthly_installments', models.PositiveIntegerField(default=0, verbose_name='Mensais (parcelas)')),
                ('balloon_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Intercaladas (%)')),
                ('balloon_installments', models.PositiveIntegerField(default=0, verbose_name='Intercaladas (parcelas)')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.estate', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Condição de pagamento',
                'verbose_name_plural': 'Condições de pagamento',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SOLD_OUT', 'Esgotado'), ('CANCELLED', 'Cancelado'), ('PAUSED', 'Pausado')], max_length=16, verbose_name='Nova situação')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('note', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='management.estate', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Evento de acompanhamento',
                'verbose_name_plural': 'Eventos de acompanhamento',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='estatefacility',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='estatefacility_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='estatefacility',
            constraint=models.CheckConstraint(condition=models.Q(('total_area__isnull', True), ('total_area__gte', 0), _connector='OR'), name='estatefacility_total_area_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='estatefacility',
            unique_together={('estate', 'facility')},
        ),
    ]
