# Generated by Django 6.1 on 2026-10-05 15:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterms',
            name='balloon_installments',
            field=models.PositiveIntegerField(default=0, verbose_name='Intercaladas (parcelas)'),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Sinal (%)'),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='key_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Chaves ou habite-se (%)'),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='monthly_installments',
            field=models.PositiveIntegerField(default=0, verbose_name='Mensais (parcelas)'),
        ),
    ]
