# Generated by Django 6.1 on 2026-10-06 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_payment_terms_labels_and_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SOLD_OUT', 'Esgotado'), ('CANCELLED', 'Cancelado'), ('PAUSED', 'Pausado')], max_length=16, verbose_name='Nova situação')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('note', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='management.estate', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Evento de acompanhamento',
                'verbose_name_plural': 'Eventos de acompanhamento',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
