# Generated by Django 6.1 on 2026-10-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_tracking_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['-pk'], 'verbose_name': 'Evento de acompanhamento', 'verbose_name_plural': 'Eventos de acompanhamento'},
        ),
    ]
