# Generated by Django 6.1 on 2026-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_estate_structured_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatefacility',
            name='floor',
            field=models.IntegerField(blank=True, help_text='0 = térreo; negativo = subsolo', null=True, verbose_name='Pavimento / Andar'),
        ),
    ]
