# Generated by Django 6.1 on 2026-10-08 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_facility_label_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatefacility',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AddConstraint(
            model_name='estatefacility',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='estatefacility_quantity_positive'),
        ),
    ]
