# Generated by Django 6.1 on 2026-10-08 12:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_estatefacility_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estatefacility',
            old_name='area',
            new_name='total_area',
        ),
        migrations.RemoveField(
            model_name='estatefacility',
            name='floor',
        ),
        migrations.AlterField(
            model_name='estatefacility',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Área total (m²)'),
        ),
        migrations.AddConstraint(
            model_name='estatefacility',
            constraint=models.CheckConstraint(condition=models.Q(('total_area__isnull', True), ('total_area__gte', 0), _connector='OR'), name='estatefacility_total_area_non_negative'),
        ),
    ]
