# Generated by Django 6.1 on 2026-10-05 14:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UP_TO_DATE', 'Atualizado'), ('OUTDATED', 'Desatualizado'), ('UNAVAILABLE', 'Indisponível')], default='PENDING', max_length=32, verbose_name='Situação')),
            ],
        ),
        migrations.CreateModel(
            name='SourceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Email para contato',
                'verbose_name_plural': 'Emails para contato',
            },
        ),
        migrations.CreateModel(
            name='SourceHyperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='SourcePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', unique=True, verbose_name='Telefone')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Telefone para contato',
                'verbose_name_plural': 'Telefones para contato',
            },
        ),
    ]
