# Generated by Django 6.1 on 2026-10-08 13:01

import checklist.models
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Formatos aceitos: pdf, txt, csv, odt, ods, png, jpg, jpeg, webp, gif', upload_to=checklist.models.availability_sheet_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'csv', 'odt', 'ods', 'png', 'jpg', 'jpeg', 'webp', 'gif'])], verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Tabela de preços',
                'verbose_name_plural': 'Tabelas de preços',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(verbose_name='Mês de referência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UP_TO_DATE', 'Atualizado'), ('OUTDATED', 'Desatualizado'), ('UNAVAILABLE', 'Indisponível')], default='PENDING', max_length=32, verbose_name='Situação')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-reference_month', 'estate__name'],
            },
        ),
        migrations.CreateModel(
            name='SourceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Email para contato',
                'verbose_name_plural': 'Emails para contato',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SourceHyperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='SourcePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', unique=True, verbose_name='Telefone')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Telefone para contato',
                'verbose_name_plural': 'Telefones para contato',
                'ordering': ['phone'],
            },
        ),
    ]
