# Generated by Django 6.1 on 2026-10-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.estate', verbose_name='Empreendimento'),
        ),
        migrations.AddField(
            model_name='availabilitysheet',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='checklist.checklist', verbose_name='Checklist'),
        ),
        migrations.AddField(
            model_name='sourceemail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='sourceemail',
            name='estates',
            field=models.ManyToManyField(blank=True, related_name='source_emails', to='management.estate', verbose_name='Empreendimentos'),
        ),
        migrations.AddField(
            model_name='sourcehyperlink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='sourcehyperlink',
            name='estates',
            field=models.ManyToManyField(blank=True, related_name='source_hyperlinks', to='management.estate', verbose_name='Empreendimentos'),
        ),
        migrations.AddField(
            model_name='sourcephone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='sourcephone',
            name='estates',
            field=models.ManyToManyField(blank=True, related_name='source_phones', to='management.estate', verbose_name='Empreendimentos'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(fields=('estate', 'reference_month'), name='unique_checklist_per_estate_month', violation_error_message='Já existe um checklist para este empreendimento neste mês.'),
        ),
    ]
