# Generated by Django 6.1 on 2026-10-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.estate', verbose_name='Empreendimento'),
        ),
        migrations.AddField(
            model_name='sourceemail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='source_email',
            field=models.ManyToManyField(to='checklist.sourceemail', verbose_name='Emails para contato'),
        ),
        migrations.AddField(
            model_name='sourcehyperlink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='source_hyperlink',
            field=models.ManyToManyField(to='checklist.sourcehyperlink', verbose_name='Links de origem'),
        ),
        migrations.AddField(
            model_name='sourcephone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company', verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='source_phone',
            field=models.ManyToManyField(to='checklist.sourcephone', verbose_name='Telefones para contato'),
        ),
    ]
