# Generated by Django 6.1 on 2026-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('UP_TO_DATE', 'Atualizado'), ('OUTDATED', 'Desatualizado'), ('UNAVAILABLE', 'Indisponível'), ('AVAILABLE', 'Disponível')], default='PENDING', max_length=32, verbose_name='Situação'),
        ),
    ]
