# Generated by Django 6.1 on 2026-10-05 14:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-reference_month', 'estate__name'], 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='source_email',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='source_hyperlink',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='source_phone',
        ),
        migrations.AddField(
            model_name='checklist',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificado em'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reference_month',
            field=models.DateField(default=datetime.date(2026, 10, 1), verbose_name='Mês de referência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceemail',
            name='estates',
            field=models.ManyToManyField(blank=True, related_name='source_emails', to='management.estate', verbose_name='Empreendimentos'),
        ),
        migrations.AddField(
            model_name='sourcehyperlink',
            name='estates',
            field=models.ManyToManyField(blank=True, related_name='source_hyperlinks', to='management.estate', verbose_name='Empreendimentos'),
        ),
        migrations.AddField(
            model_name='sourcephone',
            name='estates',
            field=models.ManyToManyField(blank=True, related_name='source_phones', to='management.estate', verbose_name='Empreendimentos'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(fields=('estate', 'reference_month'), name='unique_checklist_per_estate_month', violation_error_message='Já existe um checklist para este empreendimento neste mês.'),
        ),
    ]
