# Generated by Django 6.1 on 2026-10-06 12:40

import checklist.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_move_sources_to_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Formatos aceitos: pdf, txt, csv, odt, ods, png, jpg, jpeg, webp, gif', upload_to=checklist.models.availability_sheet_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'csv', 'odt', 'ods', 'png', 'jpg', 'jpeg', 'webp', 'gif'])], verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='checklist.checklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Tabela de preços',
                'verbose_name_plural': 'Tabelas de preços',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
