# Generated by Django 6.1 on 2026-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_availability_sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceemail',
            options={'ordering': ['email'], 'verbose_name': 'Email para contato', 'verbose_name_plural': 'Emails para contato'},
        ),
        migrations.AlterModelOptions(
            name='sourcehyperlink',
            options={'ordering': ['url'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='sourcephone',
            options={'ordering': ['phone'], 'verbose_name': 'Telefone para contato', 'verbose_name_plural': 'Telefones para contato'},
        ),
    ]
