"""
Django settings for smartworker project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/

Os serviços (banco, cache, storages, email) são configurados por URLs,
interpretadas pelo django-service-urls (carregado em manage.py/wsgi.py/asgi.py).
"""

from pathlib import Path

import environ

# ==============================================================================
# 1. BASE & ENVIRONMENT SETUP
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
# Variáveis já definidas no ambiente (ex: pelo Docker Compose) têm prioridade
environ.Env.read_env(BASE_DIR / ".env")


# ==============================================================================
# 2. SECURITY & NETWORK
# ==============================================================================

DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "::1"])

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS", default=["http://localhost:8000", "http://127.0.0.1:8000"]
)


# ==============================================================================
# 3. APPLICATION DEFINITION & CORE ARCHITECTURE
# ==============================================================================

INSTALLED_APPS = [
    # Smartworker Apps
    "management.apps.ManagementConfig",
    "checklist.apps.ChecklistConfig",
    # Django Contrib Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-Party Apps
    "phonenumber_field",
    # Remove os arquivos do disco quando o registro é apagado ou o arquivo trocado
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serve os arquivos estáticos pelo gunicorn (logo após o SecurityMiddleware)
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smartworker.urls"
WSGI_APPLICATION = "smartworker.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ==============================================================================
# 4. AUTHENTICATION & USER MANAGEMENT
# ==============================================================================

AUTH_USER_MODEL = "management.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==============================================================================
# 5. SERVICE BACKENDS (DB, CACHE, STORAGE, EMAIL)
# ==============================================================================

DATABASES = {
    "default": env("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}

CACHES = {"default": env("CACHE_URL", default="memory://")}

STORAGES = {
    "default": env("STORAGE_DEFAULT", default="fs://"),
    # Troque para "manifest://" quando o nginx passar a servir os estáticos
    "staticfiles": env("STORAGE_STATICFILES", default="whitenoise+static://"),
}

MAILERS = {"default": env("MAILER_URL", default="console://")}


# ==============================================================================
# 6. INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = "pt-br"
TIME_ZONE = env("TIME_ZONE", default="America/Sao_Paulo")
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 7. STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = env("STATIC_URL", default="static/")
STATIC_ROOT = env("STATIC_ROOT", default=str(BASE_DIR / "staticfiles"))

MEDIA_URL = env("MEDIA_URL", default="media/")
MEDIA_ROOT = env("MEDIA_ROOT", default=str(BASE_DIR / "media"))
